# Generated by Django 2.0.dev20170411164641 on 2017-04-19 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20170419_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentcategory',
            name='category_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Customer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
