# Generated by Django 2.0.dev20170411164641 on 2017-04-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20170419_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.CustomerOrder'),
        ),
    ]
