# Generated by Django 2.0.dev20170411164641 on 2017-04-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20170419_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee.CustomerOrder'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
