# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20170501_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('vc_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vc_ram', models.IntegerField(default=1)),
                ('vc_clock', models.FloatField(max_length=20)),
                ('vc_name', models.CharField(max_length=250)),
                ('vc_price', models.FloatField(max_length=500)),
                ('vc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ComponentCategory')),
                ('vc_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Manufacturer')),
                ('vc_orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ComponentOrder')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_cores',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cpu_speed',
            field=models.FloatField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='hdd',
            name='hdd_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hdd',
            name='hdd_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_resolution',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='monitor',
            name='monitor_size',
            field=models.FloatField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='power_supply_wattage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
